name: deploy-uela-cars

on:
  push:
    branches:
      - main

jobs:

  
  code-quality:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check project files
        run: |
          ls -la
          echo "Checking HTML CSS JS files..."

      - name: Install HTML validator
        run: npm install -g html-validate

      - name: Validate HTML
        run: html-validate index.html

      - name: Check JavaScript syntax
        run: node --check main.js


  # CD - Deploy to GitHub Pages
  deploy:
    name: Deploy Website
    needs: code-quality
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload website files
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
