name: deploy-uela-cars

on:
  push:
    


jobs:
 deploy:
  

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

      - name: checkout repo code
        uses: actions/checkout@v5

     


     

      - name: configure github pages
        uses: actions/configure-pages@v5

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v5
